services:
  - type: web
    name: my-telegram-bot
    env: docker
    buildCommand: ./build.sh
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 10000
