services:
  - type: web
    name: my-telegram-bot
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
